# Add Devices label to any edits to Devices
Devices:
  - src/main/java/frc/robot/devices/*
  - src/main/java/frc/robot/devices/**/*

# Add OI label to any edits to OI
OI:
  - src/main/java/frc/robot/oi/*
  - src/main/java/frc/robot/oi/**/*

# Add Utilities label to any edits to Utilities
Utilities:
  - src/main/java/frc/robot/utilities/*
  - src/main/java/frc/robot/utilities/**/*

# Add Command label to any edits to a command
Command:
  - src/main/java/frc/robot/commands/*
  - src/main/java/frc/robot/commands/**/*

# Add Subsystem label to any edits to a subsystem

Subsystem:
  - src/main/java/frc/robot/subsystems/*
  - src/main/java/frc/robot/subsystems/*/**

# Add Drivetrain label to any edits to the drivetrain subsystem or any of its commands
Drivetrain:
  - src/main/java/frc/robot/subsystems/Drivetrain.java
  - src/main/java/frc/robot/commands/drivetrain/*

# Add Shooter label to any edits to the shooter subsystem or any of its commands.
Shooter:
  - src/main/java/frc/robot/subsystems/Shooter.java
  - src/main/java/frc/robot/commands/shooter/*